export const IMG_LOADING = "IMG_LOADING";
export const IMG_LOADED = "IMG_LOADED";
export const GET_IMG_FAILED = "GET_IMG_FAILED";
export const REFRESHING = "REFRESHING";
export const REFRESH_SUCCESS = "REFRESH_SUCCESS";
export const REFRESH_FAILED = "REFRESH_FAILED";
